@startuml
!define DATABASE_COLOR #E5FFCC
!define SERVER_COLOR #FFD1DC
!define CLIENT_COLOR #D1D1E0

title Arquitetura Lógica - Aplicação de Lista de Tarefas

[Camada de Dados] DATABASE_COLOR

[Camada de Aplicação] SERVER_COLOR

[Camada de Apresentação] CLIENT_COLOR

[Camada de Dados] --> [Camada de Aplicação]

[Camada de Aplicação] --> [Camada de Apresentação]

@enduml
