@startuml
!define DATABASE_COLOR #E5FFCC
!define SERVER_COLOR #FFD1DC
!define CLIENT_COLOR #D1D1E0

title Arquitetura Lógica - Aplicação de Lista de Tarefas

top to bottom direction

package "Dados" {
    [Tarefas]
    [Usuários]
    [Categorias]
}

package "Servidor" {
    [Controlador de Sessões]
    [Controlador de Categorias]
    [Controlador de Tarefas]
}

package "Cliente" {
    [Interface Web]
}

[Usuários] --> [Categorias] : tem várias
[Categorias] --> [Tarefas] : tem várias

[Controlador de Sessões] --> [Usuários]
[Controlador de Categorias] --> [Categorias]
[Controlador de Tarefas] --> [Tarefas]

[Interface Web] --> [Controlador de Sessões]
[Interface Web] --> [Controlador de Categorias]
[Interface Web] --> [Controlador de Tarefas]

@enduml
