@startuml

skinparam actorStyle awesome

package Categorias {
  "Criar categoria de tarefas" as (criarCategoria)
  "Listar categorias com tarefas" as (listarCategorias)
  "Renomear categoria" as (renomearCategoria)
  "Reordenar categoria" as (reordenarCategoria)
  "Excluir categoria com suas tarefas" as (excluirCategoria)
}

package Tarefas {
  "Criar tarefa" as (criarTarefa)
  "Renomear tarefa" as (renomearTarefa)
  "Excluir tarefa" as (excluirTarefa)
  "Marcar tarefa como concluída" as (marcarTarefaConcluida)
  "Desmarcar tarefa como concluída" as (desmarcarTarefaConcluida)
  "Reordenar tarefa em uma categoria" as (reordenarTarefa)
}

"Usuário" as usuario

usuario -down-> (criarCategoria)
usuario -down-> (listarCategorias)
usuario -down-> (renomearCategoria)
usuario -down-> (reordenarCategoria)
usuario -up-> (excluirCategoria)

usuario -up-> (criarTarefa)
usuario -up-> (renomearTarefa)
usuario -up-> (excluirTarefa)

usuario -left-> (marcarTarefaConcluida)
usuario -left-> (desmarcarTarefaConcluida)
usuario -left-> (reordenarTarefa)

@enduml
